Log file permissions in octal format
openwall/lkrg pull request #15
Opened 2020-09-17 23:07 UTC by wsandin

Fixes #2

2020-09-17 23:19 UTC, solardiz commented on src/modules/exploit_detection/syscalls/pCFI/p_mark_inode_dirty/p_mark_inode_dirty.c
> +                    p_inode->i_ino, p_inode->i_mode);
Please add a leading zero before the `%o` to make it clear that the mode is in octal.

2020-09-17 23:20 UTC, solardiz requested changes
Please exclude whitespace and coding style edits from this PR. It's not about that.

2020-09-17 23:45 UTC, wsandin commented
Oh, wow. I can't believe I didn't catch that - my vim did automatically apply a formatter when I saved my work so opened it with `vim -u NONE ...`, but something must have went wrong. Let me fix!

2020-09-17 23:55 UTC, wsandin commented on src/modules/exploit_detection/syscalls/pCFI/p_mark_inode_dirty/p_mark_inode_dirty.c
> +                    p_inode->i_ino, p_inode->i_mode);
Done, thanks.

So there won't already be a 0 prepended like "0600" for a file? That was my assumption, but yeah I noticed you mentioning this in the issue and weren't able to trigger the print statement to test it fully.

2020-09-18 07:07 UTC, solardiz approved these changes
Now this is just the same one change I'd have made. Thanks. I hope you'll be contributing on less trivial issues as well. :-)

2020-09-18 07:07 UTC, merged

2020-09-18 07:11 UTC, solardiz commented on src/modules/exploit_detection/syscalls/pCFI/p_mark_inode_dirty/p_mark_inode_dirty.c
> +                    p_inode->i_ino, p_inode->i_mode);
As you can see, Linux kernel itself does this explicit leading zero thing on similar messages:

```
$ grep -r 'print.* mode .*%o' .
./fs/nfsd/vfs.c:	dprintk("nfsd: permission 0x%x%s%s%s%s%s%s%s mode 0%o%s%s%s\n",
./include/trace/events/writeback.h:	TP_printk("dev %d,%d ino %lu dirtied %lu state %s mode 0%o",
./include/trace/events/ext4.h:	TP_printk("dev %d,%d orig_ino %lu ino %lu mode 0%o uid %u gid %u",
./include/trace/events/ext4.h:	TP_printk("dev %d,%d ino %lu mode 0%o uid %u gid %u blocks %llu",
./include/trace/events/ext4.h:	TP_printk("dev %d,%d dir %lu mode 0%o",
./include/trace/events/ext4.h:	TP_printk("dev %d,%d ino %lu dir %lu mode 0%o",
./include/trace/events/ext4.h:	TP_printk("dev %d,%d ino %lu mode 0%o block %llu count %lu flags %s",
./include/trace/events/ext4.h:	TP_printk("dev %d,%d ino %lu mode 0%o is_metadata %d block %llu",
./include/trace/events/ext4.h:	TP_printk("dev %d,%d ino %lu mode 0%o i_blocks %llu used_blocks %d "
./include/trace/events/ext4.h:	TP_printk("dev %d,%d ino %lu mode 0%o i_blocks %llu "
./include/trace/events/ext4.h:	TP_printk("dev %d,%d ino %lu mode 0%o i_blocks %llu freed_blocks %d "
```

Userspace (libc's) `printf` doesn't prepend a leading zero on `%o` on its own. I think the kernel's doesn't either. Ideally, you'd test this by temporarily patching LKRG so that the `p_print_log` is triggered without an exploit.

2020-09-18 10:30 UTC, wsandin commented
@solardiz Thank you very much for the help, it's a bit of an honor to contribute to Openwall projects after using your software and patches for decades.

Indeed - that's my goal - I just wanted to start with a couple simpler issues to get started. C Programming and deep internals of the Linux kernel is something I'm still learning, but I also keep my eyes open for tickets related to the `build/CI`, `Makefile` etc. I'll keep my eyes on upcoming issues, and see if I can suggest any of my own.