Rework the logging infrastructure.
openwall/lkrg pull request #16
Opened 2020-09-28 20:09 UTC by oshogbo

For know we will use instrumentation function to log the entry and return of the
function. This reduce the size of code for over 10%.

Signed-off-by: Mariusz Zaborski <oshogbo@vexillium.org>

2020-10-02 15:48 UTC, solardiz requested changes
I've skimmed through these changes. They mostly look good to me. (We had discussed them conceptually via e-mail a few months ago, so I don't repeat that here.)

Please fix at least the double-unlock bug. While at it, please also fix grammar in the commit message.

2020-10-02 15:48 UTC, solardiz commented on src/modules/database/JUMP_LABEL/p_arch_jump_label_transform/p_arch_jump_label_transform.c
>  }
Per my reading, this `BUG_ON` would be triggered if `register_kretprobe()` returns a value greater than 0. Perhaps that's impossible, but I don't like the `BUG_ON`. We can instead change the check of `register_kretprobe()` return value from:

```c
   if ( (p_ret = register_kretprobe(&p_arch_jump_label_transform_kretprobe)) < 0) {
```

to:

```c
   if ((p_ret = register_kretprobe(&p_arch_jump_label_transform_kretprobe))) {
```

so that we'll treat any non-zero return as an error right there. I've just checked that all (two) calls of `p_install_arch_jump_label_transform_hook()` merely care if the return value is 0 or not, but to be on the safe side (not potentially returning a positive value on error) and to simplify the code I think we should also drop `p_ret` (including the `int p_ret;` at the start of the function) and simply `return -1;` in there.

And then we should simply `return 0;` at the end of the function.

2020-10-02 15:48 UTC, solardiz commented on src/modules/database/JUMP_LABEL/p_arch_jump_label_transform_apply/p_arch_jump_label_transform_apply.c
>  }
Ditto, let's drop `p_ret`. There's only one call to `p_install_arch_jump_label_transform_apply_hook()`, which only cares for 0 or not.

2020-10-02 15:48 UTC, solardiz commented on src/modules/database/arch/x86/p_switch_idt/p_switch_idt.c
>  }
Ditto, let's drop `p_ret`. There's only one call to `p_install_switch_idt_hook()`, which only cares for 0 or not.

2020-10-02 15:48 UTC, solardiz commented on src/modules/database/p_database.c
>     p_text_section_unlock();
Looks like you've introduced a double-unlock bug there in one of the code paths. Fixing it will probably also let you simplify the code and get rid of `p_ret` in this function.

2020-10-02 15:48 UTC, solardiz commented on src/modules/exploit_detection/p_exploit_detection.c
>  }
The changes to `p_ed_pcfi_validate_sp()` took me a while to review with the indentation change. I find them reasonable, but we should note somewhere that this isn't just a cosmetic change, but a user-visible one: when the stack frame is wrong in more than one way, the function will now complain in the logs about one of those only. It used to complain about all. Adam might want to weigh in on accepting this user-visible change or not. I am fine with it.

2020-10-02 15:48 UTC, solardiz commented on src/modules/exploit_detection/syscalls/p_install.c
>  }
Unrelated to changes of this PR, but we have the same problem of potentially returning a value greater than zero if `register_kretprobe()` returns it. So the new `BUG_ON` in other similar functions were also inconsistent with how we ignore that problem in this one. And maybe we should change this one to only return -1 or 0 for consistency with those (after my proposed changes to them). We can't fully drop `p_ret` from here as we check it for -22, but we can choose to never propagate it further like we wouldn't in those functions.

2020-10-02 15:48 UTC, solardiz commented on src/modules/ksyms/p_resolve_ksym.c
> +   int p_ret = P_LKRG_SUCCESS;
Per my reading, with further changes we never make use of the initial value of `p_ret` in this function. We might nevertheless keep the initialization as defensive programming against future changes. I have no strong preference on this.

Alternatively, we can simplify the conditional compilation logic so that we check for 5.7.0+ just once and then both define the local variables and use them in the same piece. In fact, we probably don't need separate `p_ret` and `p_tmp`, as with these changes they serve the same purpose that Adam normally uses the name `p_tmp` for.

2020-10-02 15:56 UTC, solardiz commented
Suggested commit message (more than just the grammar fixes I was going to suggest at first):

```
Rework debug logging of entry and return from functions

Use instrumentation.  This reduces source code size by over 10%.

Signed-off-by: Mariusz Zaborski <oshogbo@vexillium.org>
```

2020-10-11 01:21 UTC, Adam-pi3 commented
Sorry for delay, I will review this PR soon. In the mean time I want to mention that we should not use BUG_ON at all. Various kernel configuration might be causing kprobes to fail. That's why LKRG prints appropriate message during each step of initialization. Some of the kprobes failures goes into ISRA  / CONSTPROP path some of them don't (maybe we should always go to this logic). 
Nevertheless, please avoid using BUG_ON since I don't think in LKRG case it's useful.

2020-10-19 08:29 UTC, solardiz commented
@oshogbo Unless you're happy rebasing these changes over and over, I think you should update them per my feedback (which is consistent with Adam's - both of us were unhappy with `BUG_ON`), make them apply again, and we should get them merged sooner rather than later. Thanks.

2020-10-19 15:25 UTC, oshogbo commented on src/modules/database/p_database.c
>     p_text_section_unlock();
Nice catch!

2020-10-19 15:25 UTC, oshogbo commented on src/modules/exploit_detection/syscalls/p_install.c
>  }
This is something that @Adam-pi3 should look into.
I'm fine with changing this.

2020-10-19 15:27 UTC, oshogbo commented on src/modules/ksyms/p_resolve_ksym.c
> +   int p_ret = P_LKRG_SUCCESS;
Yea I changed p_tmp to p_ret.

2020-10-19 15:58 UTC, solardiz commented on src/modules/database/JUMP_LABEL/p_arch_jump_label_transform/p_arch_jump_label_transform.c
>  }
I see you're simply dropping the `BUG_ON` in the force-push now, but my suggestion was more elaborate, as above? Are you going to implement that or do you suggest we first merge your changes and then clean them up separately?

2020-10-19 16:08 UTC, oshogbo commented on src/modules/database/JUMP_LABEL/p_arch_jump_label_transform/p_arch_jump_label_transform.c
>  }
Yea, I would like to change this separately with more detailed commit msg.

2020-10-19 18:56 UTC, merged

2020-10-20 01:48 UTC, Adam-pi3 requested changes

2020-10-20 01:48 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
Up to this I think is fine.

2020-10-20 01:48 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
>  }
Yes, current version only complain on first error. We would want to have in the logs all violations not just first one. I would prefer to keep it how it was since it's more valuable.

2020-10-20 01:48 UTC, Adam-pi3 commented on src/modules/database/p_database.c
> +      return P_LKRG_GENERAL_ERROR;
By mistake, you've removed this return. Current version doesn't exit p_create_database() function in case of this error. That's wrong.

2020-10-20 01:48 UTC, Adam-pi3 commented on src/modules/database/p_database.c
> +      return P_LKRG_GENERAL_ERROR;
Same here

2020-10-20 01:48 UTC, Adam-pi3 commented on src/modules/database/p_database.c
>     p_text_section_unlock();
I think it is still not fixed, is it?

2020-10-20 01:48 UTC, Adam-pi3 commented on src/modules/exploit_detection/syscalls/p_install.c
>  }
I think for now it's OK.

2020-10-20 01:48 UTC, Adam-pi3 commented on src/modules/kmod/p_kmod_notifier.c
> + *  - Kernel's modules module notifier
I think it's deleted comment as well - at least that's how it looks in my browser

2020-10-20 01:48 UTC, Adam-pi3 commented on src/modules/print_log/p_lkrg_debug_log.c
> +   // Disable to noisy.
typo s/to/too/g

2020-10-20 01:48 UTC, Adam-pi3 commented on src/modules/print_log/p_lkrg_debug_log.c
> +} p_addr_name_array[] = {
I think not all the functions are on the list here. E.g. p_init_page_attr is missing.