umh: Add lkrg.umh_preexists_files sysctl.
openwall/lkrg pull request #28
Opened 2020-11-19 16:47 UTC by oshogbo

UMH contains a list of files that are allowed to execute.
LKRG during the load checks if the file exists; if so, the file is added to
the whitelist. The umh_preexists_files allows controlling this check.
By disabling lkrg.umh_prexists_files sysctl, all the files from the
lists will be allowed no matter if they were created after LKRG was loaded.

2020-11-19 16:59 UTC, solardiz requested changes
Thank you for working on this, but:

The sysctl addition is unacceptable. We should make this change unconditionally. Part of the reason for it is to simplify LKRG. This PR as it is complicates LKRG, so is counterproductive.

2020-11-19 17:03 UTC, solardiz commented
Re-implementing this without the sysctl will enable simplifications not seen here: the list of allowed pathnames should become `const` and be used directly, without copying it onto stack. The Booleans should be dropped from it.

2020-11-19 17:09 UTC, oshogbo commented
I see I was pretty sure that @Adam-pi3 wanted to leave the UMH as-it-is? Did something changed?
(we didn't discuss this particular change before).

2020-11-19 17:13 UTC, solardiz commented
We have to decide on it one way or the other. No point in having it both ways. Adam didn't fully agree with me, but in the end replied with "OK." to my "Let's not overcomplicate things." in a message CC'ed to you. So my reading is he's OK with us simplifying this unconditionally.

@Adam-pi3 Please confirm this or correct me. Thanks!

2020-11-19 17:56 UTC, Adam-pi3 commented
Hi. Sorry for the inaccuracy. I'm fine with dropping our current logic (dynamic creation of the list on the stack - even it has a lot of security advantages) and switch to the simplified version. The only hard-requirement is to be sure that list is being kept in the RO-page.
As we discussed with @solardiz it's better to NOT keep it in our internal RO-page and I like the @solardiz idea of being it as a part of the .text section. I think this should be the ideal situation.
@oshogbo would you mind going to that direction?

Thanks,
Adam

2020-11-26 17:26 UTC, oshogbo commented
I addressed your suggestions.

2020-11-26 20:49 UTC, solardiz commented on src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
> +static const char *p_umh_global[] = {
Should be `static const char * const` so that both the strings and the pointers to them are constant. See how we have it e.g. for `p_log_level_string`.

2020-11-26 20:52 UTC, solardiz commented
Please fix the commit message grammar, e.g. changing it to:

```
UMH: Allow all the pathnames listed in p_umh_global.

Previously, we'd only allow pathnames present in the filesystem at LKRG startup.
Now we don't require them to be present in the filesystem.
```

Please also edit this PR's title.

2020-11-26 20:53 UTC, oshogbo commented on src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
> +static const char *p_umh_global[] = {
Fixed.

2020-11-27 08:04 UTC, solardiz approved these changes
Overall, this looks good to me. It's obvious enough that it got to work, but I think it's good practice to always mention what testing was (not) done on each proposed change, so I'd appreciate having that info in a comment in this PR. Thanks!

2020-11-27 08:04 UTC, solardiz commented on src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
> +    }
What's happened to the indentation here?

2020-11-27 08:04 UTC, solardiz commented on src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
> +};
The indentation of this initializer is greater than we currently use in LKRG, but if these are tabs then it'll eventually be consistent with the Linux kernel coding style that we should move to.

We didn't previously have a comma after the last entry in this list. I don't mind having one, though.

2020-11-27 08:07 UTC, solardiz commented
@oshogbo If you're going to amend the commit in any way (such as for the indentation), please also adjust the commit message further to:

```
UMH: Allow all the pathnames listed in p_umh_global

Previously, we'd only allow pathnames present in the filesystem at LKRG
startup.  Now we don't require them to be present in the filesystem.
```

(Wrap the long line. Let's keep them to at most 75 chars since `git log` shows them indented by 4.)

2020-11-27 17:28 UTC, oshogbo commented on src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
> +};
Those aren't tabs. I will fix them according to the rest of LKRG (3 spaces).

2020-11-27 17:29 UTC, oshogbo commented on src/modules/exploit_detection/syscalls/p_call_usermodehelper/p_call_usermodehelper.c
> +    }
Sorry I used wrong vim config ;/

2020-11-27 22:30 UTC, merged