Rework selinux architecture
openwall/lkrg pull request #57
Opened 2021-03-17 23:14 UTC by oshogbo

### Description
* Rework the SELinux architecture.
Separate SELlinux to a new file
Introduce API for SELinux related orations.
Deduplicat code.

* Add support for kernels with rand structs (CONFIG_GCC_PLUGIN_RANDSTRUCT option).
In this case we disable SELinux monitoring.

* Add support for kernels newer then 5.6 the (CONFIG_SECURITY_SELINUX_DISABLE option)
Reflect changes in the selinux_status struct.

### How Has This Been Tested?
On ubuntu machine with custom 5.11.6 kernel build.
I used p_vuln to implement overwriting the selinux_status struct fields, and checked if the kernel will panic and if the original value will be restored.

2021-03-18 00:54 UTC, Adam-pi3 requested changes

2021-03-18 00:54 UTC, Adam-pi3 commented on src/modules/exploit_detection/p_exploit_detection.c
> +           p_lkrg_counter_lock_unlock(&p_ed_guard_globals.p_selinux_lock, &p_flags);
Why do you unlock the lock here? I think it's wrong.

2021-03-18 19:38 UTC, oshogbo commented on src/modules/exploit_detection/p_exploit_detection.c
> +           p_lkrg_counter_lock_unlock(&p_ed_guard_globals.p_selinux_lock, &p_flags);
Yes, this was from some other experiment sorry.

2021-03-19 07:26 UTC, solardiz commented
Suggested replacement commit messages, mostly just fixing typos:

```
SELinux: Refactor state monitoring

Introduce a new API for SELinux state monitoring.
Move the API to a separate file.
```

```
SELinux: Recognize that the disable parameter is optional

Starting with Linux 5.6 a new config option was introduced:
CONFIG_SECURITY_SELINUX_DISABLE. Reflect in LKRG selinux_struct
that the "disabled" flag is optional for these newer kernels.
```

```
SELinux: Disable state monitoring for kernels with rand structs

New Linux kernels may be built with the CONFIG_GCC_PLUGIN_RANDSTRUCT
option. This is option randomly changes the order of fields in structures.
The selinux_state structure has this attribute. Currently, LKRG isn't capable to
recreate the structure layout.

To make LKRG available on kernels with this option, we disable
SELinux monitoring.

CONFIG_GCC_PLUGIN_RANDSTRUCT was introduced to make it harder
for attackers to overwrite particular fields of the structure.
LKRG's goal was the same. So even disabling LKRG's monitoring,
we still have some mitigations for the selinux_state structure.

We expect future work to make LKRG capable to recreate randomized
structures.
```

2021-03-19 07:47 UTC, solardiz commented on src/p_lkrg_main.h
> +#endif
I don't really mind this hack, but I wonder if the `#undef CONFIG_SECURITY_SELINUX_DEVELOP` can possibly cause inconsistencies in kernel headers if we include any further ones after this point. Ideally, we'd introduce and use our own macro for whether we're monitoring SELinux state. I think this would also let us avoid nested `#if` in a few places.

2021-03-19 13:32 UTC, oshogbo commented
@solardiz I have changed the commit messages.

2021-03-19 13:36 UTC, oshogbo commented on src/p_lkrg_main.h
> +#endif
Right now most of our includes are in single file and p_lkrg_main.h is the last one that we include - so i'm not sure if this is an issue for now.
But in general terms I totally agree that this would be a cleaner solution.
TBH I'm not sure if we would avoid nested `#if` . Do you have any particular one in mind?

2021-03-19 15:09 UTC, Adam-pi3 commented on src/p_lkrg_main.h
> +#endif
We already do similar checks e.g., here:
https://github.com/openwall/lkrg/blob/main/src/modules/exploit_detection/p_exploit_detection.h#L64

Similar work can be done in SELinux file where you define e.g., P_SELINUX_VERIFY variable which depends on CONFIG_SECURITY_SELINUX_DEVELOP and CONFIG_GCC_PLUGIN_RANDSTRUCT. Later you rely on P_SELINUX_VERIFY instead of CONFIG_SECURITY_SELINUX_DEVELOP

2021-03-19 20:18 UTC, oshogbo commented on src/p_lkrg_main.h
> +#endif
Yes I'm understand the idea - I just not sure which part of code it will remove nested `#if`s ?

2021-03-19 20:29 UTC, solardiz commented on src/p_lkrg_main.h
> +#endif
I took a closer look, and I now think I was wrong - this won't let us remove nested `#if`s, at least not on its own.

2021-03-19 20:30 UTC, solardiz approved these changes
I think this is OK to merge. Adam?

2021-03-19 21:20 UTC, Adam-pi3 commented on src/p_lkrg_main.h
> +#endif
I still think it's a good idea to introduce P_SELINUX_VERIFY. @oshogbo can you do it?

2021-03-19 21:21 UTC, Adam-pi3 commented
> I think this is OK to merge. Adam?

I think current version is OK. As soon as @oshogbo introduces P_SELINUX_VERIFY we can merge it.

2021-03-19 22:11 UTC, oshogbo commented on src/p_lkrg_main.h
> +#endif
Sure. Done.

2021-03-19 22:16 UTC, Adam-pi3 approved these changes

2021-03-19 22:17 UTC, merged

2021-03-20 09:58 UTC, solardiz commented
> On ubuntu machine with custom 5.11.6 kernel build.
> I used p_vuln to implement overwriting the selinux_status struct fields, and checked if the kernel will panic and if the original value will be restored.

@oshogbo You might want to rerun these tests for the merged code now, as it's slightly different. Thanks!